# Generated by Django 5.2.3 on 2025-06-18 21:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Password',
            field=models.CharField(default='pass123', max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='Emp_Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Contact',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit number. Optional +91 at the start.', regex='^(\\+91)?\\d{10}$')]),
        ),
    ]
