# Generated by Django 5.2.3 on 2025-06-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employee_password_alter_department_emp_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Password',
            field=models.CharField(max_length=100),
        ),
    ]
